-- The checklist that defines a complete brand profile.
insert into field_defs (key, category, label, help, required, multi, sort) values
('legal_name','Identity','Legal business name','The name on the paperwork, if it differs from the trading name.',false,false,10),
('trading_name','Identity','Trading name','What customers actually call you.',true,false,20),
('one_liner','Identity','One-line description','What you do, in a sentence a stranger would understand.',true,false,30),
('founded_year','Identity','Year founded',null,false,false,40),
('owner_story','Identity','Founder story','Why this business exists. The single richest source of post material.',true,false,50),
('mission','Identity','Mission or promise',null,false,false,60),
('services','Offer','Services or products','One per fact. What you sell.',true,true,110),
('pricing','Offer','Pricing or price range','Even a range. Customers ask this more than anything else.',true,true,120),
('service_area','Offer','Service area','Where you will and will not travel.',true,false,130),
('lead_times','Offer','Lead time or availability',null,false,false,140),
('guarantees','Offer','Guarantees, warranty or returns',null,false,false,150),
('differentiators','Offer','What makes you different','Why someone picks you over the place down the road.',true,true,160),
('ideal_customer','Audience','Ideal customer',null,true,false,210),
('customer_problems','Audience','Problems you solve','One per fact.',true,true,220),
('objections','Audience','Common objections','What people hesitate over before buying.',false,true,230),
('competitors','Audience','Named competitors',null,false,true,240),
('reviews_summary','Proof','What reviews say','Themes from Google, Yelp, elsewhere.',false,false,310),
('case_examples','Proof','Notable jobs or clients',null,false,true,320),
('credentials','Proof','Licences, certifications, awards',null,false,true,330),
('team','Proof','Team members worth naming',null,false,true,340),
('tone','Voice','Tone of voice','Formal, blunt, warm, funny. Pick words you would actually use.',true,false,410),
('vocabulary','Voice','Words you use','House terms and phrases.',false,true,420),
('banned_words','Voice','Words to never use','The corporate filler that makes you cringe.',false,true,430),
('post_examples','Voice','Past posts worth imitating',null,false,true,440),
('hours','Operations','Opening hours',null,true,false,510),
('contact_phone','Operations','Phone number',null,true,false,520),
('contact_email','Operations','Contact email',null,true,false,530),
('address','Operations','Address',null,false,false,540),
('booking_url','Operations','Booking or quote link',null,false,false,550),
('social_handles','Operations','Social profiles','One per fact, with the platform name.',false,true,560),
('seasonality','Calendar','Busy and slow seasons','Drives when campaigns should run.',false,false,610),
('recurring_events','Calendar','Recurring events or promos',null,false,true,620),
('announcements','Calendar','Anything coming up','New hires, new kit, new location.',false,true,630)
on conflict (key) do nothing;
